services:
  db:
    image: postgres:17-alpine
    container_name: smart-ops-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - node-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  back-end:
    image: ghcr.io/vmestrada88/smart-ops-back-end:production
    container_name: smart-ops-backend
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=${DB_SSL}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - FRONTEND_URLS=${FRONTEND_URLS}
    ports:
      - "5000:5000"
    networks:
      - node-network
    depends_on:
      db:
        condition: service_healthy

  front-end:
    image: ghcr.io/vmestrada88/smart-ops-front-end:production
    container_name: smart-ops-frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - back-end


volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  node-network:
    driver: bridge
